### ISSUE TITLE
图表坐标轴真机显示好像有问题

### ISSUE THREAD

**Issue by flytam** [xiabingwu/chartjs-wechat-mini-app#11]
真机上是这样的
![default](https://user-images.githubusercontent.com/20512530/36516384-a198724e-17b8-11e8-8ebb-47d4ef3fd6bc.png)
模拟器是这样的
![mmm](https://user-images.githubusercontent.com/20512530/36516393-acbe779a-17b8-11e8-89c7-1c113d8bb987.png)
请问要怎样解决，好像chartjs上没有看到相关的配置

**Comment by crazyurus** [comment]
遇到了类似的问题，基础库版本高于1.9.9时出现，之前是好的

**Comment by flytam** [comment]
@crazyurus 有解决办法吗

**Comment by crazyurus** [comment]
@673800357 修改了fixedCtx.js中ctx.measureText方法*4改成了*10缓解了这个问题，没有彻底解决
